//! A variety of DOM utility functions.

use or_poisoned::OrPoisoned;
#[cfg(debug_assertions)]
use reactive_graph::diagnostics::SpecialNonReactiveZone;
use reactive_graph::owner::Owner;
use send_wrapper::SendWrapper;
use std::time::Duration;
use tachys::html::event::EventDescriptor;
#[cfg(feature = "tracing")]
use tracing::instrument;
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
use wasm_bindgen::{JsCast, JsValue, UnwrapThrowExt, prelude::Closure};

#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
#[allow(missing_docs)]
pub mod mock {
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub struct JsValue;
    impl JsValue {
        pub fn undefined() -> Self { JsValue }
    }
    
    pub trait JsCast: Sized {
        fn unchecked_into<T>(self) -> T { panic!() }
        fn unchecked_ref(&self) -> &Self { self }
    }
    impl JsCast for JsValue {}

    pub mod web_sys {
        #[allow(unused_imports)]
        use super::JsValue;
        
        #[derive(Clone, Debug)]
        pub struct Window;
        #[derive(Clone, Debug)]
        pub struct Document;
        #[derive(Clone, Debug)]
        pub struct Element;
        #[derive(Clone, Debug)]
        pub struct Location;
        #[derive(Clone, Debug)]
        pub struct Event;
        #[derive(Clone, Debug)]
        pub struct HtmlInputElement;
        
        impl super::JsCast for Window {}
        impl super::JsCast for Document {}
        impl super::JsCast for Element {}
        impl super::JsCast for Location {}
        impl super::JsCast for Event {}
        impl super::JsCast for HtmlInputElement {}

        impl Window {
            pub fn location(&self) -> Location { Location }
        }
        impl Location {
            pub fn set_href(&self, _val: &str) -> Result<(), JsValue> { Ok(()) }
        }
    }
}

#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
use mock::{JsCast, JsValue, web_sys};

// ==========================================
// --- Shared Handles & Structs (Isomorphic) ---
// ==========================================

/// Handle that is generated by [request_animation_frame_with_handle] and can
/// be used to cancel the animation frame request.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct AnimationFrameRequestHandle(i32);

impl AnimationFrameRequestHandle {
    /// Cancels the animation frame request to which this refers.
    /// See [`cancelAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame)
    pub fn cancel(&self) {
        #[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
        {
            _ = window().cancel_animation_frame(self.0);
        }
    }
}

/// Handle that is generated by [request_idle_callback_with_handle] and can be
/// used to cancel the idle callback.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct IdleCallbackHandle(u32);

impl IdleCallbackHandle {
    /// Cancels the idle callback to which this refers.
    /// See [`cancelAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelIdleCallback)
    pub fn cancel(&self) {
        #[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
        {
            window().cancel_idle_callback(self.0);
        }
    }
}

/// Handle that is generated by [set_timeout_with_handle] and can be used to clear the timeout.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct TimeoutHandle(i32);

impl TimeoutHandle {
    /// Cancels the timeout to which this refers.
    /// See [`clearTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout)
    pub fn clear(&self) {
        #[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
        {
            window().clear_timeout_with_handle(self.0);
        }
    }
}

/// Handle that is generated by [set_interval] and can be used to clear the interval.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct IntervalHandle(i32);

impl IntervalHandle {
    /// Cancels the repeating event to which this refers.
    /// See [`clearInterval()`](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval)
    pub fn clear(&self) {
        #[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
        {
            window().clear_interval_with_handle(self.0);
        }
    }
}

/// A handle that can be called to remove a global event listener.
pub struct WindowListenerHandle(Box<dyn FnOnce() + Send + Sync>);

impl core::fmt::Debug for WindowListenerHandle {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_tuple("WindowListenerHandle").finish()
    }
}

impl WindowListenerHandle {
    /// Removes the event listener.
    pub fn remove(self) {
        (self.0)()
    }
}

// ==========================================
// --- Browser Implementation ---
// ==========================================

#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
thread_local! {
    pub(crate) static WINDOW: web_sys::Window = web_sys::window().unwrap_throw();

    pub(crate) static DOCUMENT: web_sys::Document = web_sys::window().unwrap_throw().document().unwrap_throw();
}

/// Returns the [`Window`](https://developer.mozilla.org/en-US/docs/Web/API/Window).
///
/// This is cached as a thread-local variable, so calling `window()` multiple times
/// requires only one call out to JavaScript.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn window() -> web_sys::Window {
    WINDOW.with(Clone::clone)
}

/// Returns the [`Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document).
///
/// This is cached as a thread-local variable, so calling `document()` multiple times
/// requires only one call out to JavaScript.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn document() -> web_sys::Document {
    DOCUMENT.with(Clone::clone)
}

/// Sets a property on a DOM element.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn set_property(
    el: &web_sys::Element,
    prop_name: &str,
    value: &Option<JsValue>,
) {
    let key = JsValue::from_str(prop_name);
    match value {
        Some(value) => _ = js_sys::Reflect::set(el, &key, value),
        None => _ = js_sys::Reflect::delete_property(el, &key),
    };
}

/// Gets the value of a property set on a DOM element.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[doc(hidden)]
pub fn get_property(
    el: &web_sys::Element,
    prop_name: &str,
) -> Result<JsValue, JsValue> {
    let key = JsValue::from_str(prop_name);
    js_sys::Reflect::get(el, &key)
}

/// Returns the current [`window.location`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location).
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn location() -> web_sys::Location {
    window().location()
}

/// Current [`window.location.hash`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location)
/// without the beginning #.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn location_hash() -> Option<String> {
    if is_server() {
        None
    } else {
        location()
            .hash()
            .ok()
            .map(|hash| match hash.chars().next() {
                Some('#') => hash[1..].to_string(),
                _ => hash,
            })
    }
}

/// Current [`window.location.pathname`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location).
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn location_pathname() -> Option<String> {
    location().pathname().ok()
}

/// Helper function to extract [`Event.target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target)
/// from any event.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn event_target<T>(event: &web_sys::Event) -> T
where
    T: JsCast,
{
    event.target().unwrap_throw().unchecked_into::<T>()
}

/// Helper function to extract `event.target.value` from an event.
///
/// This is useful in the `on:input` or `on:change` listeners for an `<input>` element.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn event_target_value<T>(event: &T) -> String
where
    T: JsCast,
{
    event
        .unchecked_ref::<web_sys::Event>()
        .target()
        .unwrap_throw()
        .unchecked_into::<web_sys::HtmlInputElement>()
        .value()
}

/// Helper function to extract `event.target.checked` from an event.
///
/// This is useful in the `on:change` listeners for an `<input type="checkbox">` element.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn event_target_checked(ev: &web_sys::Event) -> bool {
    ev.target()
        .unwrap()
        .unchecked_into::<web_sys::HtmlInputElement>()
        .checked()
}

/// Runs the given function between the next repaint using
/// [`Window.requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(feature = "tracing", instrument(level = "trace", skip_all))]
#[inline(always)]
pub fn request_animation_frame(cb: impl FnOnce() + 'static) {
    _ = request_animation_frame_with_handle(cb);
}

#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
fn closure_once(cb: impl FnOnce() + 'static) -> JsValue {
    let mut wrapped_cb: Option<Box<dyn FnOnce()>> = Some(Box::new(cb));
    let closure = Closure::new(move || {
        if let Some(cb) = wrapped_cb.take() {
            cb()
        }
    });
    closure.into_js_value()
}

/// Runs the given function between the next repaint using
/// [`Window.requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame),
/// returning a cancelable handle.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(feature = "tracing", instrument(level = "trace", skip_all))]
#[inline(always)]
pub fn request_animation_frame_with_handle(
    cb: impl FnOnce() + 'static,
) -> Result<AnimationFrameRequestHandle, JsValue> {
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn raf(cb: JsValue) -> Result<AnimationFrameRequestHandle, JsValue> {
        window()
            .request_animation_frame(cb.as_ref().unchecked_ref())
            .map(AnimationFrameRequestHandle)
    }

    raf(closure_once(cb))
}

/// Queues the given function during an idle period using
/// [`Window.requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestIdleCallback).
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(feature = "tracing", instrument(level = "trace", skip_all))]
#[inline(always)]
pub fn request_idle_callback(cb: impl Fn() + 'static) {
    _ = request_idle_callback_with_handle(cb);
}

/// Queues the given function during an idle period using
/// [`Window.requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestIdleCallback),
/// returning a cancelable handle.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(feature = "tracing", instrument(level = "trace", skip_all))]
#[inline(always)]
pub fn request_idle_callback_with_handle(
    cb: impl Fn() + 'static,
) -> Result<IdleCallbackHandle, JsValue> {
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn ric(cb: Box<dyn Fn()>) -> Result<IdleCallbackHandle, JsValue> {
        let cb = Closure::wrap(cb).into_js_value();

        window()
            .request_idle_callback(cb.as_ref().unchecked_ref())
            .map(IdleCallbackHandle)
    }

    ric(Box::new(cb))
}

/// A microtask is a short function which will run after the current task has
/// completed its work and when there is no other code waiting to be run before
/// control of the execution context is returned to the browser's event loop.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn queue_microtask(task: impl FnOnce() + 'static) {
    #[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
    {
        tachys::renderer::dom::queue_microtask(task);
    }
}

/// Executes the given function after the given duration of time has passed.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(
    feature = "tracing",
    instrument(level = "trace", skip_all, fields(duration = ?duration))
)]
pub fn set_timeout(cb: impl FnOnce() + 'static, duration: Duration) {
    _ = set_timeout_with_handle(cb, duration);
}

/// Executes the given function after the given duration of time has passed, returning a cancelable handle.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(
    feature = "tracing",
    instrument(level = "trace", skip_all, fields(duration = ?duration))
)]
#[inline(always)]
pub fn set_timeout_with_handle(
    cb: impl FnOnce() + 'static,
    duration: Duration,
) -> Result<TimeoutHandle, JsValue> {
    #[cfg(debug_assertions)]
    let cb = || {
        let _z = SpecialNonReactiveZone::enter();
        cb();
    };

    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn st(cb: JsValue, duration: Duration) -> Result<TimeoutHandle, JsValue> {
        window()
            .set_timeout_with_callback_and_timeout_and_arguments_0(
                cb.as_ref().unchecked_ref(),
                duration.as_millis().try_into().unwrap_throw(),
            )
            .map(TimeoutHandle)
    }

    st(closure_once(cb), duration)
}

/// "Debounce" a callback function.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn debounce<T: 'static>(
    delay: Duration,
    mut cb: impl FnMut(T) + 'static,
) -> impl FnMut(T) {
    use std::sync::{Arc, RwLock};

    #[cfg(debug_assertions)]
    #[allow(unused_mut)]
    let mut cb = move |value| {
        let _z = SpecialNonReactiveZone::enter();
        cb(value);
    };

    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    #[allow(unused_mut)]
    let mut cb = move |value| {
        let _guard = span.enter();
        cb(value);
    };

    let cb = Arc::new(RwLock::new(cb));
    let timer = Arc::new(RwLock::new(None::<TimeoutHandle>));

    Owner::on_cleanup({
        let timer = Arc::clone(&timer);
        move || {
            if let Some(timer) = timer.write().or_poisoned().take() {
                timer.clear();
            }
        }
    });

    move |arg| {
        if let Some(timer) = timer.write().unwrap().take() {
            timer.clear();
        }
        let handle = set_timeout_with_handle(
            {
                let cb = Arc::clone(&cb);
                move || {
                    cb.write().unwrap()(arg);
                }
            },
            delay,
        );
        if let Ok(handle) = handle {
            *timer.write().or_poisoned() = Some(handle);
        }
    }
}

/// Repeatedly calls the given function, with a delay of the given duration between calls.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(
    feature = "tracing",
    instrument(level = "trace", skip_all, fields(duration = ?duration))
)]
pub fn set_interval(cb: impl Fn() + 'static, duration: Duration) {
    _ = set_interval_with_handle(cb, duration);
}

/// Repeatedly calls the given function, with a delay of the given duration between calls,
/// returning a cancelable handle.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(
    feature = "tracing",
    instrument(level = "trace", skip_all, fields(duration = ?duration))
)]
#[inline(always)]
pub fn set_interval_with_handle(
    cb: impl Fn() + 'static,
    duration: Duration,
) -> Result<IntervalHandle, JsValue> {
    #[cfg(debug_assertions)]
    let cb = move || {
        let _z = SpecialNonReactiveZone::enter();
        cb();
    };
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move || {
        let _guard = span.enter();
        cb();
    };

    #[inline(never)]
    fn si(
        cb: Box<dyn FnMut()>,
        duration: Duration,
    ) -> Result<IntervalHandle, JsValue> {
        let cb = Closure::wrap(cb).into_js_value();

        window()
            .set_interval_with_callback_and_timeout_and_arguments_0(
                cb.as_ref().unchecked_ref(),
                duration.as_millis().try_into().unwrap_throw(),
            )
            .map(IntervalHandle)
    }

    si(Box::new(cb), duration)
}

/// Adds an event listener to the `Window`, typed as a generic `Event`,
/// returning a cancelable handle.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[cfg_attr(
    feature = "tracing",
    instrument(level = "trace", skip_all, fields(event_name = %event_name))
)]
#[inline(always)]
pub fn window_event_listener_untyped(
    event_name: &str,
    cb: impl Fn(web_sys::Event) + 'static,
) -> WindowListenerHandle {
    #[cfg(debug_assertions)]
    let cb = move |e| {
        let _z = SpecialNonReactiveZone::enter();
        cb(e);
    };
    #[cfg(feature = "tracing")]
    let span = ::tracing::Span::current();
    #[cfg(feature = "tracing")]
    let cb = move |e| {
        let _guard = span.enter();
        cb(e);
    };

    if !is_server() {
        #[inline(never)]
        fn wel(
            cb: Box<dyn FnMut(web_sys::Event)>,
            event_name: &str,
        ) -> WindowListenerHandle {
            let cb = Closure::wrap(cb).into_js_value();
            _ = window().add_event_listener_with_callback(
                event_name,
                cb.unchecked_ref(),
            );
            let event_name = event_name.to_string();
            let cb = SendWrapper::new(cb);
            WindowListenerHandle(Box::new(move || {
                _ = window().remove_event_listener_with_callback(
                    &event_name,
                    cb.unchecked_ref(),
                );
            }))
        }

        wel(Box::new(cb), event_name)
    } else {
        WindowListenerHandle(Box::new(|| ()))
    }
}

/// Creates a window event listener from a typed event, returning a
/// cancelable handle.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn window_event_listener<E: EventDescriptor + 'static>(
    event: E,
    cb: impl Fn(E::EventType) + 'static,
) -> WindowListenerHandle
where
    E::EventType: JsCast,
{
    window_event_listener_untyped(&event.name(), move |e| {
        cb(e.unchecked_into::<E::EventType>())
    })
}

/// Returns `true` if the current environment is a server.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn is_server() -> bool {
    #[cfg(feature = "hydration")]
    {
        Owner::current_shared_context()
            .map(|sc| !sc.is_browser())
            .unwrap_or(false)
    }
    #[cfg(not(feature = "hydration"))]
    {
        false
    }
}

/// Returns `true` if the current environment is a browser.
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
pub fn is_browser() -> bool {
    !is_server()
}

// ==========================================
// --- Non-Browser Implementation (Stubs) ---
// ==========================================

/// Returns the [`Window`](https://developer.mozilla.org/en-US/docs/Web/API/Window).
///
/// Under WASI or native server targets, calling this function will panic.
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn window() -> web_sys::Window {
    panic!("window() is not available in a non-browser environment")
}

/// Returns the [`Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document).
///
/// Under WASI or native server targets, calling this function will panic.
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn document() -> web_sys::Document {
    panic!("document() is not available in a non-browser environment")
}

/// Sets a property on a DOM element (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn set_property(
    _el: &web_sys::Element,
    _prop_name: &str,
    _value: &Option<JsValue>,
) {
}

/// Gets the value of a property set on a DOM element (Stub - returns undefined).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
#[doc(hidden)]
pub fn get_property(
    _el: &web_sys::Element,
    _prop_name: &str,
) -> Result<JsValue, JsValue> {
    Ok(JsValue::undefined())
}

/// Returns the current [`window.location`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location).
///
/// Under WASI or native server targets, calling this function will panic.
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn location() -> web_sys::Location {
    panic!("location() is not available in a non-browser environment")
}

/// Current [`window.location.hash`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) (Stub - returns None).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn location_hash() -> Option<String> {
    None
}

/// Current [`window.location.pathname`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) (Stub - returns None).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn location_pathname() -> Option<String> {
    None
}

/// Helper function to extract [`Event.target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) (Stub - panics).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn event_target<T>(_event: &web_sys::Event) -> T
where
    T: JsCast,
{
    panic!("event_target() is not available in a non-browser environment")
}

/// Helper function to extract `event.target.value` (Stub - returns empty string).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn event_target_value<T>(_event: &T) -> String
where
    T: JsCast,
{
    String::new()
}

/// Helper function to extract `event.target.checked` (Stub - returns false).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn event_target_checked(_ev: &web_sys::Event) -> bool {
    false
}

/// Runs the given function between the next repaint (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn request_animation_frame(_cb: impl FnOnce() + 'static) {}

/// Runs the given function between the next repaint, returning a cancelable handle (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn request_animation_frame_with_handle(
    _cb: impl FnOnce() + 'static,
) -> Result<AnimationFrameRequestHandle, JsValue> {
    Ok(AnimationFrameRequestHandle(0))
}

/// Queues the given function during an idle period (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn request_idle_callback(_cb: impl Fn() + 'static) {}

/// Queues the given function during an idle period, returning a cancelable handle (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn request_idle_callback_with_handle(
    _cb: impl Fn() + 'static,
) -> Result<IdleCallbackHandle, JsValue> {
    Ok(IdleCallbackHandle(0))
}

/// A microtask is a short function (Stub - executes task immediately).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn queue_microtask(task: impl FnOnce() + 'static) {
    task();
}

/// Executes the given function after the given duration of time has passed (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn set_timeout(_cb: impl FnOnce() + 'static, _duration: Duration) {}

/// Executes the given function after the given duration of time has passed, returning a cancelable handle (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn set_timeout_with_handle(
    _cb: impl FnOnce() + 'static,
    _duration: Duration,
) -> Result<TimeoutHandle, JsValue> {
    Ok(TimeoutHandle(0))
}

/// "Debounce" a callback function (Stub - routes immediately to cb).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn debounce<T: 'static>(
    _delay: Duration,
    mut cb: impl FnMut(T) + 'static,
) -> impl FnMut(T) {
    move |arg| {
        cb(arg);
    }
}

/// Repeatedly calls the given function, with a delay of the given duration between calls (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn set_interval(_cb: impl Fn() + 'static, _duration: Duration) {}

/// Repeatedly calls the given function, returning a cancelable handle (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn set_interval_with_handle(
    _cb: impl Fn() + 'static,
    _duration: Duration,
) -> Result<IntervalHandle, JsValue> {
    Ok(IntervalHandle(0))
}

/// Adds an event listener to the `Window`, returning a cancelable handle (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn window_event_listener_untyped(
    _event_name: &str,
    _cb: impl Fn(web_sys::Event) + 'static,
) -> WindowListenerHandle {
    WindowListenerHandle(Box::new(|| ()))
}

/// Creates a window event listener from a typed event, returning a cancelable handle (Stub - does nothing).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn window_event_listener<E: EventDescriptor + 'static>(
    _event: E,
    _cb: impl Fn(E::EventType) + 'static,
) -> WindowListenerHandle
where
    E::EventType: JsCast,
{
    WindowListenerHandle(Box::new(|| ()))
}

/// Returns `true` if the current environment is a server (Always true on non-browser targets).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn is_server() -> bool {
    true
}

/// Returns `true` if the current environment is a browser (Always false on non-browser targets).
#[cfg(not(all(target_arch = "wasm32", target_os = "unknown")))]
pub fn is_browser() -> bool {
    false
}
